### ISSUE TITLE
swaggy starting styles

### ISSUE THREAD

**Issue by Papillard** [lewagon/rails-stylesheets#1]
Ce serait pas mal de changer 2-3 style (police et taille de texte pr headers / core texts / navbar). Les choix sont assez discutables (ex: les titres sont un peu trop gros et gras en Montserrat, la navbar est en capitalize..) bref y a clairement des choses améliorables. Il faut simplement changer qqs variables SASS de google fonts et de tailles dans `_variables.scss`, `_bootstrap_variables.scss` et `_navbar.scss`. 

Quitte a leur donner un dossier de stylesheets de démarrage autant qu'il ait le swagomètre au max ! @tchret tu peux nous faire une petite PR la-dessus? C'est plus une PR de bon gout qu'une PR de code :)

**Comment by ssaunier** [comment]
@Papillard est-ce que tu as pu bosser un peu dessus ? On ferme ?
