### ISSUE TITLE
SASSC not included by default

### ISSUE THREAD

**Issue by ajdubovoy** [lewagon/rails-stylesheets#30]
Hi @Eschults 👋 

`sassc-rails` is no longer included by default, so I'd love to change the `README` to say:

```md
Ensure you have the following gems in your Rails `Gemfile`:

\`\`\`ruby
gem "sassc-rails"
gem "bootstrap", "~> 5.2"
gem "autoprefixer-rails"
gem "font-awesome-sass", "~> 6.1"
gem "simple_form"
\`\`\`
```

But I don't have push access for this repo. Would it be possible to add me?

Thanks so much 🙌

**Comment by Eschults** [comment]
👋 @ajdubovoy, done in https://github.com/lewagon/rails-stylesheets/commit/46b72ddc0402dd92e2c8d438d4ac1663a0b5f5f6, and you now have push access 👇 

<img width="1551" alt="Screenshot 2024-03-06 at 12 46 02" src="https://github.com/lewagon/rails-stylesheets/assets/8090140/cffa29e6-517d-4e00-bd0b-b0c88ea259c5">

**Comment by ajdubovoy** [comment]
Thank you!
